fix: precreate /var/lib/openstack-helm/tmp
Fixes:

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/var/lib/openstack/lib/python3.10/site-packages/oslo_service/service.py", line 810, in run_service
    service.start()
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/common/rpc_service.py", line 60, in start
    self._real_start()
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/conductor/rpc_service.py", line 36, in _real_start
    super()._real_start()
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/common/rpc_service.py", line 88, in _real_start
    self.manager.init_host(admin_context)
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/conductor/base_manager.py", line 181, in init_host
    self._collect_periodic_tasks(admin_context)
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/conductor/base_manager.py", line 321, in _collect_periodic_tasks
    for ifaces in driver_factory.all_interfaces().values():
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/common/driver_factory.py", line 284, in all_interfaces
    return {iface: interfaces(iface) for iface in _INTERFACE_LOADERS}
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/common/driver_factory.py", line 284, in <dictcomp>
    return {iface: interfaces(iface) for iface in _INTERFACE_LOADERS}
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/common/driver_factory.py", line 275, in interfaces
    return _get_all_drivers(_INTERFACE_LOADERS[interface_type]())
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/common/driver_factory.py", line 336, in __init__
    self.__class__._init_extension_manager()
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/common/driver_factory.py", line 407, in _init_extension_manager
    stevedore.NamedExtensionManager(
  File "/var/lib/openstack/lib/python3.10/site-packages/stevedore/named.py", line 78, in __init__
    extensions = self._load_plugins(invoke_on_load,
  File "/var/lib/openstack/lib/python3.10/site-packages/stevedore/extension.py", line 218, in _load_plugins
    self._on_load_failure_callback(self, ep, err)
  File "/var/lib/openstack/lib/python3.10/site-packages/ironic/common/driver_factory.py", line 358, in _catch_driver_not_found
    raise exception.DriverLoadError(driver=ep.name, reason=exc)
ironic.common.exception.DriverLoadError: Driver, hardware type or interface ipmitool could not be loaded. Reason: Path /var/lib/openstack-helm/tmp does not exist..
```